config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'lists#index'
  resources :lists, except: [:index] do
    resources :bookmarks, only: [ :new, :create ]
  end
  resources :bookmarks, only: [ :destroy ]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :list
  belongs_to :movie
  validates :movie, :list, presence: true
  validates :movie, uniqueness: { scope: :list }
  validates :comment, length: { minimum: 6 }
end

app/models/list.rb
class List < ApplicationRecord
  validates :name, uniqueness: true
  validates :name, presence: true
  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy
  has_one_attached :photo
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, uniqueness: true
  validates :overview, presence: true
  validates :title, presence: true
  has_many :bookmarks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end


# http://tmdb.lewagon.com/movie/top_rated

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_bookmark, only: [:show, :edit, :update, :destroy]
  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @movie = Movie.find(params[:bookmark][:movie_id])
    @bookmark.list = @list
    @bookmark.movie = @movie
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @list = @bookmark.list
    @bookmark.destroy
    redirect_to(list_path(@list))
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie, :list)
  end

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show, :edit, :update, :destroy]
  def index
    if params[:q]
      @keyword = params[:q]
      @flats = Flat.where("name LIKE ?", "%#{@keyword}%")
      @search_result = "Your search returned #{@flats.count} results"
    else
      @lists = List.all
    end
  end

  def show
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @list.update(list_params)
    redirect_to list_path(@list)
  end

  def destroy
    @list.destroy
    redirect_to lists_path
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end

  def set_list
    @list = List.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/new.html.erb
<%= simple_form_for ([ @list, @bookmark ]) do |f| %>
  <%= f.input :comment %>
  <%= f.association :list%>
  <%= f.association :movie%>
  <%= f.submit "Submit", class: "btn btn-primary" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
   <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<div class='container'>
  <%= simple_form_for(list) do |f|%>
    <%= f.input :name%>
    <%= f.input :photo, as: :file %>
    <%= f.submit class:'btn btn-primary' %>
  <% end %>
</div>

app/views/lists/edit.html.erb
<%= render "form", flat: @flat %>

app/views/lists/index.html.erb
<div class='nav'>
  <h1><%= link_to('Movies Lists', lists_path) %></h1>
  <div>
  <form>
    <input name='q' type='search' placeholder='Search'>
    <button type='Submit'>Search</button>
  </form>
  <%= link_to('Add a new List', new_list_path)%>
  </div>
</div >
<%= cl_image_tag("bejl2biievokbsirenmg",
      width: 100, height: 300, crop: :fill) %>

<ul>
  <% @lists.each do |list| %>
  <li>
    <h2><%= list.name%></h2>
    <div>
    <span><%= link_to 'More info', list_path(list) %></span>
    <span><%= link_to 'Edit', edit_list_path(list) %></span>
    </div>
  </li>
  <% end %>
</ul>

app/views/lists/new.html.erb
<%= render "form", list: @list %>

app/views/lists/show.html.erb
<div class='container'>
  <div>
    <div class='header'>
      <h1>List name: <%= @list.name %></h1>
      <% @list.bookmarks.each do |bookmark|%>
        <h3>Bookmark comment: <%= bookmark.comment%></h3>
        <h3>Bookmark movie: <%= bookmark.movie.title%></h3>
         <p><%= link_to 'Delete bookmark', bookmark_path(bookmark),
                    method: :delete,
                     data: { confirm: "Are you sure?" }%></p>
      <% end %>
      <%= link_to('Add a bookmark', new_list_bookmark_path(@list)) %>
    <%= link_to('Back to list', lists_path) %>
  </div>
</div>